// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Products → Specs*
 */
export interface ProductsDocumentDataSpecsItem {
  /**
   * Spec field in *Products → Specs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.g., 400W - 550W capacity
   * - **API ID Path**: products.specs[].spec
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  spec: prismic.KeyTextField;
}

/**
 * Content for Products documents
 */
interface ProductsDocumentData {
  /**
   * Name field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the name of the Product
   * - **API ID Path**: products.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Category field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Which Category it is ?
   * - **API ID Path**: products.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Image field in *Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Give a short description about the product
   * - **API ID Path**: products.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Highlight field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Give a Highlight of this product
   * - **API ID Path**: products.highlight
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  highlight: prismic.KeyTextField;

  /**
   * Specs field in *Products*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: products.specs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  specs: prismic.GroupField<Simplify<ProductsDocumentDataSpecsItem>>;
}

/**
 * Products document from Prismic
 *
 * - **API ID**: `products`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductsDocumentData>,
    "products",
    Lang
  >;

/**
 * Item in *Work → Images*
 */
export interface WorkDocumentDataImagesItem {
  /**
   * Image field in *Work → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Work → Details*
 */
export interface WorkDocumentDataDetailsItem {
  /**
   * Details field in *Work → Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Give some overview details about your work
   * - **API ID Path**: work.details[].details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  details: prismic.KeyTextField;
}

/**
 * Item in *Work → Benefits*
 */
export interface WorkDocumentDataBenefitsItem {
  /**
   * Benefit field in *Work → Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Write the benefits of your works
   * - **API ID Path**: work.benefits[].benefit
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  benefit: prismic.KeyTextField;
}

/**
 * Item in *Work → Timeline*
 */
export interface WorkDocumentDataTimelineItem {
  /**
   * Phase field in *Work → Timeline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Facility Analysis
   * - **API ID Path**: work.timeline[].phase
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phase: prismic.KeyTextField;

  /**
   * Duration field in *Work → Timeline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 2-3 Weeks
   * - **API ID Path**: work.timeline[].duration
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  duration: prismic.KeyTextField;
}

/**
 * Content for Work documents
 */
interface WorkDocumentData {
  /**
   * Images field in *Work*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<WorkDocumentDataImagesItem>>;

  /**
   * Title field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name your work
   * - **API ID Path**: work.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Category field in *Work*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Residential
   * - **API ID Path**: work.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    "Residential" | "Commercial" | "Industrial",
    "filled"
  >;

  /**
   * Location field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Where the work did ?
   * - **API ID Path**: work.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Capacity field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the Capacity (e.g. 100KW)
   * - **API ID Path**: work.capacity
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  capacity: prismic.KeyTextField;

  /**
   * Savings field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: How much customer saves ?(e.g. ₹5,00,000 annually)
   * - **API ID Path**: work.savings
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  savings: prismic.KeyTextField;

  /**
   * Completion field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: When it was completed ?
   * - **API ID Path**: work.completion
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  completion: prismic.KeyTextField;

  /**
   * ShortDesc field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Write a short description of your work
   * - **API ID Path**: work.shortdesc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  shortdesc: prismic.KeyTextField;

  /**
   * Full Desc field in *Work*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write a detailed description about your work
   * - **API ID Path**: work.full_desc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  full_desc: prismic.RichTextField;

  /**
   * Details field in *Work*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.details[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  details: prismic.GroupField<Simplify<WorkDocumentDataDetailsItem>>;

  /**
   * Benefits field in *Work*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.benefits[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  benefits: prismic.GroupField<Simplify<WorkDocumentDataBenefitsItem>>;

  /**
   * Timeline field in *Work*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.timeline[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  timeline: prismic.GroupField<Simplify<WorkDocumentDataTimelineItem>>;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes = ProductsDocument | WorkDocument;

/**
 * Default variation for Details Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DetailsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Details*
 */
type DetailsSliceVariation = DetailsSliceDefault;

/**
 * Details Shared Slice
 *
 * - **API ID**: `details`
 * - **Description**: Details
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DetailsSlice = prismic.SharedSlice<
  "details",
  DetailsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ProductsDocument,
      ProductsDocumentData,
      ProductsDocumentDataSpecsItem,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataImagesItem,
      WorkDocumentDataDetailsItem,
      WorkDocumentDataBenefitsItem,
      WorkDocumentDataTimelineItem,
      AllDocumentTypes,
      DetailsSlice,
      DetailsSliceVariation,
      DetailsSliceDefault,
    };
  }
}
